# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# github image repository
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aim-on
  TAG: latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set-up python ${{ matrix.python-version }} enviroments
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Login to Github Container Registry(GCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    
    - name: Build and Push docker image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
